import { Router } from 'express';
import { z } from 'zod';
import { generateStructured, AIServiceError } from '../ai/aiService.js';
import { analysisSchema, roadmapSchema, questionsSchema, gradeSchema, summarySchema, feedbackSchema, resumeBuildSchema } from '../ai/schemas.js';

const router = Router();
const MAX_CONTENT = 30000;
const difficulties = ['easy', 'medium', 'hard'];
const profileColumns = 'id, full_name, degree, college, location, target_role, experience_level, bio, github_url, linkedin_url, portfolio_url, notifications_enabled, ai_model_preference';
const ok = (res, data) => res.json(data);
const fail = (res, message, code = 400) => res.status(code).json({ status: 'error', message });

router.post('/interview/start', async(req,res)=>{const input=z.object({role:z.string(),interviewType:z.string().optional(),difficulty:z.string().optional(),count:z.number().optional()}).parse(req.body);const role=input.role.trim(), interviewType=(input.interviewType||'technical').trim(), difficulty=difficulties.includes((input.difficulty||'medium').trim())?(input.difficulty||'medium').trim():'medium',count=Math.min(Math.max(input.count||5,3),8);if(role.length<2)return fail(res,'Please enter the role you want to interview for.');try{const {questions}=await generateStructured({schema:questionsSchema,task:'reasoning',temperature:.7,system:'You are a senior technical interviewer conducting a mock interview for a fresh graduate. Ask clear, realistic questions that progress in difficulty.',prompt:`Generate exactly ${count} ${interviewType} interview questions for a "${role}" position at "${difficulty}" difficulty. Return only the questions.`});const transcript=questions.slice(0,count).map(question=>({question}));const {data:row,error}=await req.supabase.from('interviews').insert({user_id:req.user.id,role,interview_type:interviewType,difficulty,status:'active',transcript}).select('id').single();if(error)throw error;return ok(res,{status:'success',session:{id:row.id,role,interviewType,difficulty,status:'active',transcript,overallScore:null,summary:null}})}catch(e){console.error(e);return fail(res,e instanceof AIServiceError?e.message:'Could not start the interview. Please try again.',500)}});

router.post('/interview/answer', async(req,res)=>{const input=z.object({interviewId:z.string(),questionIndex:z.number(),answer:z.string()}).parse(req.body);const trimmed=input.answer.trim();if(trimmed.length<2)return ok(res,{ok:false,message:'Please type an answer before submitting.'});try{const {data:row,error}=await req.supabase.from('interviews').select('role,difficulty,status,transcript').eq('id',input.interviewId).maybeSingle();if(error)throw error;if(!row)return ok(res,{ok:false,message:'Interview not found.'});if(row.status!=='active')return ok(res,{ok:false,message:'This interview is already complete.'});const transcript=row.transcript||[],turn=transcript[input.questionIndex];if(!turn)return ok(res,{ok:false,message:'Invalid question.'});const grade=await generateStructured({schema:gradeSchema,task:'reasoning',temperature:.3,system:'You are an expert interviewer grading a candidate answer. Be fair and specific. Score on correctness, clarity, depth, and relevance.',prompt:`Role: ${row.role} (${row.difficulty}).\nQuestion: ${turn.question}\nCandidate answer: ${trimmed}\n\nGrade this answer.`});turn.answer=trimmed.slice(0,4000);turn.score=grade.score;turn.feedback=grade.feedback;const {error:updateError}=await req.supabase.from('interviews').update({transcript,updated_at:new Date().toISOString()}).eq('id',input.interviewId);if(updateError)throw updateError;return ok(res,{ok:true,turn})}catch(e){console.error(e);return ok(res,{ok:false,message:e instanceof AIServiceError?e.message:'Could not grade your answer. Please try again.'})}});

router.post('/interview/finish', async(req,res)=>{const {interviewId}=z.object({interviewId:z.string()}).parse(req.body);try{const {data:row,error}=await req.supabase.from('interviews').select('role,difficulty,transcript').eq('id',interviewId).maybeSingle();if(error)throw error;if(!row)return ok(res,{ok:false,message:'Interview not found.'});const graded=(row.transcript||[]).filter(t=>typeof t.score==='number');if(!graded.length)return ok(res,{ok:false,message:'Answer at least one question first.'});const overallScore=Math.round(graded.reduce((s,t)=>s+(t.score||0),0)/graded.length);let summary='Interview completed. Review the per-question feedback above to see where you can improve.';try{const result=await generateStructured({schema:summarySchema,task:'reasoning',temperature:.5,system:'You are an interview coach summarizing a mock interview for a fresh graduate. Be encouraging but honest, highlighting strengths and the top areas to improve.',prompt:`Role: ${row.role} (${row.difficulty}). Overall score: ${overallScore}/100.\nTranscript:\n${graded.map((t,i)=>`Q${i+1}: ${t.question}\nAnswer: ${t.answer}\nScore: ${t.score}/100\n`).join('\n')}\nWrite the overall assessment.`});summary=result.summary}catch(e){console.error(e)}const {error:updateError}=await req.supabase.from('interviews').update({status:'completed',overall_score:overallScore,summary,updated_at:new Date().toISOString()}).eq('id',interviewId);if(updateError)throw updateError;await req.supabase.from('activities').insert({user_id:req.user.id,type:'interview',title:'Mock Interview Completed',subtitle:`${row.role} · ${row.difficulty}`,score:`${overallScore}/100`});return ok(res,{ok:true,overallScore,summary})}catch(e){return fail(res,'Could not finish the interview.',500)}});

router.post('/interview/history', async(req,res)=>{try{const {data,error}=await req.supabase.from('interviews').select('id,role,interview_type,difficulty,status,overall_score,created_at').order('created_at',{ascending:false}).limit(10);if(error)throw error;return ok(res,data||[])}catch(e){return fail(res,'Could not load interview history.',500)}});
export default router;
